---
title: "Progress-report-jnwhalen"
author: "Jenna Whalen"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## GitHub Documents

```{r}
library(Lahman)
head(HallOfFame, 3)
```
## Reading
```{r}
library(dplyr)
library(readr)
library(ggplot2)
```

```{r}
library(rvest)
url <- "https://www.baseball-reference.com/awards/hof_2025.shtml"
html <- read_html(url)
tables <- html_table(html)
head(tables[[1]], 3)
```

```{r}
data <- tables[[1]]
actual_col_names <- data[1, ]
colnames(data) <- actual_col_names
data <- data[-1, ]
head(data, 3)
```

## Cleaning
```{r}
tables <- html %>% html_elements("table") %>% html_table(fill = TRUE)

valid_names <- names(data) != "" & !is.na(names(df))

df <- tables[[1]]

data$Votes <- readr::parse_number(data$Votes)
data$`%vote` <- readr::parse_number(data$`%vote`)
data$Name <- gsub("X-", "", data$Name)
data$Name <- gsub("\\.", "", data$Name)    # Remove periods
data$Name <- gsub("  ", " ", data$Name)    # Fix double spaces
head(data, 3)
```

```{r}
HallOfFame_2025 <- data.frame(
  yearID = 2025,
  votedBy = "BBWAA",
  ballots = as.numeric(data$Votes),
  needed = NA,
  votes = as.numeric(data$Votes),
  inducted = ifelse(as.numeric(data$`%vote`) >= 75, "Y", "N"),
  category = "Player"
)
```
